services:
  postgres:
    image: postgres:15
    ports: [5432:5432]
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - my-bridge

  policy-service:
    image: 'ruby:3.3'
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    env_file:
      - .env
    ports: [3001:3001]
    depends_on:
      postgres:
        condition: service_healthy
    tty: true
    stdin_open: true
    networks:
      - my-bridge

volumes:
  database:
  rubygems:

networks:
  my-bridge:
    name: my-bridge
