services:
  postgres:
    image: postgres:15
    ports: [5432:5432]
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - my-bridge

  policy-service:
    image: 'ruby:3.3'
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    ports: [3001:3001]
    depends_on:
      postgres:
        condition: service_healthy
    tty: true
    stdin_open: true
    networks:
      - my-bridge
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && rails s -b 0.0.0.0 -p 3001"
  
  workers:
    image: 'ruby:3.3'
    env_file:
      - .env
    working_dir: /app
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && WORKERS=PolicyWorker rake sneakers:run"
    networks:
      - my-bridge
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - policy-service

volumes:
  database:
  rubygems:

networks:
  my-bridge:
    name: my-bridge
